---
title: ""
listing: 
  - id: R_classes
    contents: "/r/*/index.qmd"
    type: table
    fields: [title, date, description]
    sort: "date asc"
    filter-ui: false
    sort-ui: false
  - id: Unix_classes
    contents: "/unix/*/index.qmd"
    type: table
    fields: [title, date, description]
    sort: "date asc"
    filter-ui: false
    sort-ui: false
page-layout: full
title-block-banner: false
---


::: {#hero-heading}

:::


## R classes

::: {#R_classes}
:::

:::{.panel-tabset}

# Scripts from classes

::: {#Scripts_from_class}

[Video on how to create an R project](media/Create_project.mp4)

- Fall 2023 - R basics
  - Tuesdays group
    1. [September 19th](scripts_for_class/script_class2t.R)
    2. [September 19th (2)](scripts_for_class/class_19092023.R)
    2. [October 3rd](scripts_for_class/script_class2tuesday.R)
    3. [October 10th](scripts_for_class/class_10102023.R)
    3. [October 17th](scripts_for_class/class_17102023.R)
  - Fridays group
    1. [September 15th](scripts_for_class/script_class1f.R)
    2. [September 29th](scripts_for_class/class_29092023.R)
    3. [October 6th](scripts_for_class/class_06102023.R)
    4. [October 19th](scripts_for_class/class_19102023.R)

:::

# Datasets for classes

- [Class1_exampleData.txt](/exampleData/Class1_exampleData.txt)
- [TimeSeries_example.csv](/exampleData/TimeSeries_example.csv)
- [Reductases.fasta](/exampleData/Reductases.fasta)
- [Col-0.bam file](/exampleData/subset_Col_0_GFP_1_Aligned.sortedByCoord.out.bam)
- [Col-0.bam.bai file](/exampleData/subset_Col_0_GFP_1_Aligned.sortedByCoord.out.bam.bai)
- [Arabidopsis_counts.csv](/exampleData/Arabidopsis_counts.csv)
:::

## Unix classes

::: {#Unix_classes}
:::

:::{.panel-tabset}

# Scripts for class

- Scripts for the class 4:
	- [myTry.sh](scripts_for_class/myTry.sh)
	- [myGeneralBlast.sh](scripts_for_class/myGeneralBlast.sh)
	- [sbatch_blast.sh](scripts_for_class/sbatch_blast.sh)
	- [create_master_blast.sh](scripts_for_class/create_master_blast.sh)


# Datasets for class

- [prots.fasta](https://karengoncalves.quarto.pub/files-for-class/prots.fasta)
- [blastn_result.txt](https://karengoncalves.quarto.pub/files-for-class/blastn_result)
- [input_subset.fasta](https://karengoncalves.quarto.pub/files-for-class/input_subset.fasta)

:::
